# Generated by Django 5.0 on 2023-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
