# Generated by Django 5.0 on 2023-12-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_catergoy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
