# Generated by Django 5.0 on 2023-12-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_product_catergoy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, choices=[('Lewis', 'Lewis'), ('FCUK', 'FCUK'), ('Pepe', 'Pepe')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
