# Generated by Django 5.0 on 2023-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_product_brand_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_picture'),
        ),
    ]
